schrodinger/pymol-open-source

- .gitattributes
On Windows, `.pkl` files get corrupted due to the conversion of line endings when cloning pymol from github.
For example, the Electrostatics demo fails with 
```
Load-Error: Unable to load file 'X:\Python37\lib\site-packages\pymol\pymol_path\data/demo/pept.pkl'.
Selector-Error: Invalid selection name "pept".
( pept )<--
Exception in thread Thread-3:
Traceback (most recent call last):
File "X:\Python37\lib\threading.py", line 917, in _bootstrap_inner
self.run()
File "X:\Python37\lib\threading.py", line 865, in run
self._target(*self._args, **self._kwargs)
File "X:\Python37\lib\site-packages\pymol\wizard\demo.py", line 378, in elec
self.cmd.hide("(pept)")
File "X:\Python37\lib\site-packages\pymol\viewing.py", line 665, in hide
return _showhide(representation, selection, 0, _self)
File …
```
> Fix corruption of .pkl files on Windows

- create_shadertext.py
so that /usr/lib64/python2.7/site-packages/pymol/_cmd.so in
openSUSE's python-pymol package builds in a reproducible way
in spite of indeterministic filesystem readdir order
and http://bugs.python.org/issue30461
See https://reproducible-builds.org/ for why this is good.
> Sort input file list

- modules/pymol/querying.py
I needed an overlap command that don't be larger if there are more atoms, so I had to look for what exactly `cmd.overlap` does, and it values is larger for bigger selections. Just documented it.
> Document the overlap command

- modules/pymol/importing.py
The structure 4WQF has chains with two letter codes. This commit allow `fetch` to import such chains (eg. `fetch 4WQF.BZ`).
> Support fetching two letter chains

- setup.py
Is more sane and is a lot less trickier to embed the PyMOL window inside another program because the window id is related to PID directly as there is no sh process leftover anymore.
> Add exec call to launcher

- layer0/os_predef.h
- ov/src/ov_port.h
- ov/src/ov_types.h
On musl libc, ptrdiff_t, the type used in this header's typedefs, isn't
pulled in by any other include, so it is necessary to include <cstddef>
directly.
> Include <cstddef> in ov_types.h.

- layer2/CifFile.cpp
See https://jira.schrodinger.com/browse/SHARED-7269 in Schrödinger bug tracking.
When a .cif file had windows line endings, we weren't treating
long cif data values correctly. Basically, we were
including the carriage return character in the data value!
A .cif long value looks like this:
_pdbx_struct_assembly_gen.asym_id_list
;A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,AA,BA,CA,DA,EA,FA,GA,HA,IA,JA,KA,LA,MA,NA,OA,PA,QA,RA,SA,TA,UA,VA,WA,XA,YA,ZA,AB,BB,CB,DB,EB,FB,GB,HB,IB
;
where the key is "_pdbx_struct_assembly_gen.asym_id_list" and
the value is everything between the semicolons, excluding the
final line break. Before this commit, we removed a single
linebreak character before the `;`. After this commit, we
remove one or two line break characters.
This wouldn't show up in …
> Crash reading some .cif files with Windows line endings

- layer2/Mol2Typing.cpp
The SYBYL atom typing for Sulphoxide sulphur (S.o) and Sulphone sulphur (S.o2) doesn't match the SYBYL nomenclature (https://www.sdsc.edu/CCMS/Packages/cambridge/pluto/atom_types.html)
> Fixing SYBYL atom types for Sulphoxide sulphur (S.o) and Sulphone sulphur (S.o2)

- layer3/Selector.cpp
The underlying issue could be the negative value of `base[0].sele[a]` or the signed/unsigned mismatch of `base[0].sele[a]` and `AtomInfoType.flags` (less likely, but I don't know...).
Casting to a `bool` fixes this particular issue.
Closes https://github.com/schrodinger/pymol-open-source/issues/198
> Fix guide selector bug

- modules/pymol/util.py
This patch adds a `subsele` argument to the `get_sasa_relative` command. It allows me to query relative side chain exposure.
Example:
```
fetch 1ubq
get_sasa_relative polymer, subsele=sidechain
```
> get_sasa_relative: Add subsele argument

- layer1/Setting.cpp
The `fetch_path` setting is usually not meaningful across different computers. Opening a session file which has `fetch_path` set to a location which doesn't exist on the current computer will make the `fetch` command fail to save files.
> Add `fetch_path` to `is_session_blacklisted`

- layer2/ObjectMolecule.cpp
- layer3/ExecutivePython.cpp
- Allow `discrete=0` for multi-state objects
- Keep existing discrete flag with `discrete=-1`
Fixes https://github.com/schrodinger/pymol-open-source/issues/212
> More consistent cmd.load_model discrete behavior

- setup.py
This PR add the possibility to use the latest VTK-m release (v.1.7) when compiling PyMOL
> Allow building with latst vtk-m release (v1.7)

- layer1/P.cpp
- modules/chempy/mmtf/__init__.py
- modules/chempy/mmtf/io.py
- modules/pymol/importing.py
Fixes `chempy.mmtf` with `msgpack-python` 1.0.
Also makes it work with `cmd.load_raw` and pass the corresponding tests.
Fixes https://github.com/schrodinger/pymol-open-source/issues/225
> Fix fallback MMTF loader

- modules/pmg_tk/skins/normal/__init__.py
This is a PR for Issue #189. The original issue report mentions this workaround but a PR was never created. Absence of this workaround makes Tk PyMol unusable.
> Fix for missing scene panel dialog in Tk GUI

- layer1/P.cpp
- layer1/P.h
- layer2/AtomInfo.h
- layer5/PyMOL.cpp
- layer5/PyMOL.h
- modules/pymol/completing.py
Add `explicit_valence` (sum of bond orders) and `explicit_degree` (number of directly-bonded neighbors) to `cmd.iterate`. These properties should be equivalent to [OBAtom::GetExplicitValence()](https://openbabel.github.io/api/3.0/classOpenBabel_1_1OBAtom.shtml#a3037ede30cf1ba5fe88d85f0e215e53a), [OBAtom::GetExplicitDegree()](https://openbabel.github.io/api/3.0/classOpenBabel_1_1OBAtom.shtml#ad5700b224315119362b624867f0e9aa4) and [RDKit::Atom::getDegree()](https://www.rdkit.org/docs/source/rdkit.Chem.rdchem.html#rdkit.Chem.rdchem.Atom.GetDegree).
Example:
```python
from pymol import cmd
def test_explicit_degree():
cmd.reinitialize()
cmd.fragment("ala")
result = []
cmd.iterate("all", "result.append(explicit_degree)", space=locals())
assert result == [2, 4, 2, 1, 4, 1, 1, 1, 1, 1]
def …
```
> iterate: Add explicit_valence and explicit_degree

- modules/pymol/invocation.py
Allows you to put your `.pymolrc` at `~/.config/pymol/pymolrc` to adhere to the XDG_CONFIG_HOME standard
> Use XDG_CONFIG_HOME for pymolrc

- layer0/Crystal.cpp
- layer1/Setting.cpp
- layer1/SettingInfo.h
- layer2/CoordSet.cpp
- layer2/ObjectMolecule.cpp
Add a new setting to render the `cell` representation centered.
```
fragment trp
set_symmetry trp, 8, 8, 8, 90, 90, 90, P1
show cell
```
```
set cell_centered
```
Closes https://github.com/schrodinger/pymol-open-source/issues/258
> New setting: cell_centered

- layer2/RepCartoon.cpp
Fixes crash for
```
fetch 2xwu, type=cif, discrete=1
```
Follow-up on "PYMOL-3840 Fix cartoon rep memory init" 682572b9789cca856ea2be37bf707acdfb3e3bbb
> Fix crash when loading discrete object

- contrib/mmtf-c/mmtf_parser.cpp
Floats may be stored as integers in msgpack, and msgpack-cpp does that proactively since version 4.1.2. That broke the `unitCell` angle round trip in [testSave_symmetry__mmtf](https://github.com/schrodinger/pymol-testing/blob/ca649bf79409e92e7ae419d384dc610bffd118ca/tests/api/exporting.py#L281-L295).
See also:
https://github.com/rcsb/mmtf-c/pull/35
https://github.com/msgpack/msgpack-c/pull/1018
> Fix testSave_symmetry__mmtf for msgpack-cpp=4.1.2

- layer0/PyMOLEnums.h
- layer1/Ortho.cpp
- layer1/SceneRender.cpp
- layer1/Setting.cpp
- layer1/SettingInfo.h
This patch is a possible solution for https://github.com/schrodinger/pymol-open-source/issues/267, implemented as a background texture. It adds a new `bg_gradient` mode.
Example:
```
fragment ala
fragment cys
fragment gly
set grid_mode
set bg_gradient, 2
set bg_image_linear, 0
```
To facilitate a nice implementation, I first refactored the `bg_grad` function in a separate commit.
> grid mode background color per grid cell

- layer0/ShaderMgr.cpp
Known workaround for glew initialization under wayland error that seems to be a glew build issue.
> Workaround shader disable encountered in combination with wayland

- layer1/Scene.cpp
This pull request optimizes the number of columns and rows in grid mode. Previously, you could easily end up with a 3x2 instead of 2x2 grid with 4 elements, or a 4x2 instead of 3x2 grid for 5 elements.
Example:
```
set grid_mode
viewport 800, 400
fragment gly, m1
fragment gly, m2
fragment gly, m3
fragment gly, m4
```
| Current master        | This Pull Request  |
| ------------- |-----|
| ![grid-old](https://user-images.githubusercontent.com/1239490/216675906-1a0039f5-b48c-46b5-bd71-f8dde8984ba4.png) | ![grid-new](https://user-images.githubusercontent.com/1239490/216675382-3be2cdce-758e-4eb7-aaae-6d107350b033.png) |
> Avoid 3x2 grid for size=4

- layer4/Cmd.cpp
The following functions were releasing the GIL and then calling Python functions:
- CmdCombineObjectTTT
- CmdTransformObject
- CmdTransformSelection
- CmdGetObjectTTT
Fixed by either moving the Python calls outside the unblocked API context, or by using a blocked API context.
Observed as a crash after clicking the "Properties" dialog button, which calls `cmd.get_object_ttt`.
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==46349==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000010 (pc 0x7f09b5d253d3 bp 0x000000000010 sp 0x7ffed0cf7a80 T0)
==46349==The signal is caused by a READ memory access.
==46349==Hint: address points to the zero page.
#0 0x7f09b5d253d3 in PyList_New (/usr/lib/libpython3.10.so.1.0+0x1253d3)
#1 …
```
> Fix GIL for get_object_ttt and friends

- layer2/MmtfMoleculeReader.cpp
Fixes https://github.com/schrodinger/pymol-open-source/issues/295
> MMTF loader: Use entityList for HETATM flag

- modules/pmg_qt/volume.py
Related to https://github.com/Pymol-Scripts/Pymol-script-repo/issues/136
> Fix volume editor for Python 3.10

- layer1/Scene.cpp
Regression of d0a3380636e3d4079a0320b372a330dcf797d660
This causes an infinite loop:
```
set grid_mode
delete *
```
> Fix infinite loop with grid_mode and no objects

- layer1/SceneMouse.cpp
- layer2/AtomInfo.h
- layer2/ObjectMolecule.cpp
- layer2/Sculpt.cpp
- layer3/Selector.cpp
Introducing an `enum` for `AtomInfoType::protekted`.
I tried to understand the [protect](https://pymolwiki.org/index.php/Protect) command better and this refactoring helped.
> Refactoring: enum cAtomProtected_*

- layer3/Selector.h
- layer3/SelectorTmp.cpp
Fall back to `SelectorCountAtoms()` if `m_count == 0`, which is the case for named selections.
Fixes https://github.com/schrodinger/pymol-open-source/issues/322
> Fix SelectorTmp::getAtomCount() w/ selection name

- layer0/MyPNG.cpp
See https://github.com/pnggroup/libpng/issues/534
The bug report says that `png_check_sig` was deprecated many years ago.
> Fix for broken `png_check_sig` in libpng 1.6.41

- testing/conftest.py
- testing/pytest.ini
- testing/testing.py
- testing/tests/api/importing.py
_Migrated from https://github.com/schrodinger/pymol-testing/pull/10_
Supports running all tests with:
```sh
cd testing
python -m pytest
```
Result with latest (Sep 1, 2023) pymol-open-source:
```
====== 654 passed, 331 skipped, 1 warning in 40.53s ======
```
Result with incentive pymol 2.5.6:
```
====== 767 passed, 218 skipped, 1 warning in 43.11s ======
```
Because `mmlibs` and `undo` tests are [not supported by PyMOL 2.5](https://github.com/schrodinger/pymol-testing/issues/9), I disabled them by default.
> Support running all tests with pytest, make --no-mmlibs --no-undo the default

- modules/pmg_qt/pymol_qt_gui.py
Fix the "Settings > Colors..." panel. Sliders need `int` value.
```
Traceback (most recent call last):
File ".../pmg_qt/pymol_qt_gui.py", line 576, in update_gui
form.slider_R.setValue(R * 100)
TypeError: setValue(self, a0: int): argument 1 has unexpected type 'float'
```
> Fix colors panel

- create_shadertext.py
- modules/pymol/plugins/installation.py
- testing/tests/system/pymolwin.py
Python 3.12 has removed `distutils`: https://docs.python.org/3.12/whatsnew/3.12.html#removed
> replace distutils for python 3.12

- testing/tests/helpers/test_utils.py
Fixes https://github.com/schrodinger/pymol-open-source/issues/370
Solution is similar to https://github.com/schrodinger/pymol-open-source/blob/86ff2c3be6548c48f2e414e47036915ef3aaba7e/testing/testing.py#L87-L94
> Fix test_utils.compatible_with

- layer2/CoordSet.cpp
- layer2/CoordSet.h
- layer3/MoleculeExporter.cpp
- testing/tests/api/exporting.py
Now `cmd.get_model()` returns an atom model with the object name on it. I didn't want to use the `object` variable because it is a built-in, however I thought that any other name would be misleading.
> Add atom object name on the  `cmd.get_model()` returned model

- modules/pymol/plugins/repository.py
Use redirected filename when downloading scripts from the internet.
Fix #385.
> URL redirect on plugin installation

- create_shadertext.py
- setup.py
Allow to override build date with `SOURCE_DATE_EPOCH`
to make builds reproducible.
See https://reproducible-builds.org/ for why this is good and https://reproducible-builds.org/specs/source-date-epoch/ for the definition of this variable.
> Allow to override build date with SOURCE_DATE_EPOCH

- layer3/Selector.cpp
When using the dist command with mode=2 for structures that have sensibly placed polar hydrogens, it becomes apparent that many hydrogen bonds with very good geometry are missed. The problem only affects atom pairs in which both atoms can have a donor and an acceptor function (i.e. waters, Ser, Thr, His and ligands).
Origin of this behavior is the DistSet SelectorGetDistSet function in layer3/Selector.cpp:
if(ai1->hb_donor && ai2->hb_acceptor) {
//check for suitable geometry
} else if(ai1->hb_acceptor && ai2->hb_donor) {
//check for suitable geometry
} else {
//no hydrogen bond
}
> Fix H-bonding issue in DistSet SelectorGetDistSet

- .github/workflows/build.yml
- modules/pymol/pymolhttpd.py
- modules/pymol/shortcut.py
- pyproject.toml
- testing/tests/api/importing.py
- testing/tests/api/test_shortcut.py
- [adding libffi to windows ci pipeline](https://github.com/schrodinger/pymol-open-source/pull/435/commits/5db731467192d0a2e07720b5c1f3d894c39afbf0) - I have encountered an error in CI for the Windows platform([example](https://github.com/schrodinger/pymol-open-source/actions/runs/13354211427/job/37294680115)). 
For more information on the solution, check [this link](https://stackoverflow.com/questions/73458524/importerror-dll-load-failed-while-importing-ctypes-the-specified-module-coul/76791146#76791146).
- [bump pillow version](https://github.com/schrodinger/pymol-open-source/pull/435/commits/2147ef1e9d128d4c066bbafc920968e898065b41) - The pipelines for macOS and Windows are failing because they are using Python 3.13 with old version of PIL, which is supported only by the latest …
> fixing ci pipeline for python3.9 and python3.13

- layer1/P.cpp
- layer1/P.h
- layer3/Selector.cpp
- testing/tests/api/querying.py
Hi. This is my attempt to support the selection of delocalized atoms. I copy the following comment to turn potential limitations explicit.
```C++
// simple rule which gets all aromatic C atoms right, but can
// be wrong for example for neutral aromatic N atoms with degree 3 or
// for neutral carboxy O atoms which PyMOL also assigns bond oder 4.
```
I want also to detect aromatic rings. Should I do proceed?
> Attempt to detect delocalized atoms

- ov/src/OVLexicon.cpp
Fix integer overflow in hash function causing ASAN failure.
Identical codegen: https://godbolt.org/z/Ed7W1h
> Fix integer overflow in hash function.
